apiVersion: v1
kind: ConfigMap
metadata:
  name: dw-smb-bed-was-cm
  namespace: jeus
data:
  domain.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <domain xmlns="http://www.tmaxsoft.com/xml/ns/jeus" version="8.0">
            <production-mode>true</production-mode>
            <id>20180918</id>
              <admin-server-name>%SERVERNAME%</admin-server-name>
            <security-manager>
                    <default-application-domain>SYSTEM_DOMAIN</default-application-domain>
                    <security-domains>
                            <security-domain>
                                    <name>SYSTEM_DOMAIN</name>
                            </security-domain>
                    </security-domains>
            </security-manager>
            <domain-log-home>/mwlog/jeus</domain-log-home>
            <session-cluster>
                    <cluster-mode>DOMAIN_WIDE</cluster-mode>
                    <session-manager-provider>REDIS</session-manager-provider>
                    <exclude-das-in-cluster>false</exclude-das-in-cluster>
                    <sticky-encoding-rule>BASE64</sticky-encoding-rule>
                    <common-cluster-config>
                            <reserved-thread-num>0</reserved-thread-num>
                            <connect-timeout>5000</connect-timeout>
                            <read-timeout>20000</read-timeout>
                            <allow-fail-back>true</allow-fail-back>
                            <failover-strategy>none</failover-strategy>
                            <backup-level>access</backup-level>
                            <backup-unit-size>50</backup-unit-size>
                            <backup-queue-size>20</backup-queue-size>
                            <ignore-flow-control>false</ignore-flow-control>
                            <failover-delay>600</failover-delay>
                            <restart-delay>600</restart-delay>
                            <passivation>
                                    <trigger>
                                            <timeout>-1</timeout>
                                            <count-threshold>-1</count-threshold>
                                            <memory-threshold>-1</memory-threshold>
                                    </trigger>
                                    <single-folder-file-limit>10000</single-folder-file-limit>
                                    <min-hole>100</min-hole>
                                    <packing-rate>0.5</packing-rate>
                                    <ratio>0.7</ratio>
                            </passivation>
                    </common-cluster-config>
                    <properties>
                            <property>
                                    <key>redis-architecture</key>
                                    <value>CLUSTER</value>
                            </property>
                            <property>
                                    <key>redis-nodes</key>
                                    <value>redis://192.168.179.13:7300,redis://192.168.179.13:7400,redis://192.168.179.13:7500,redis://192.168.179.13:7501,redis://192.168.179.13:7401,redis://192.168.179.13:7301</value>
                            </property>
                            <property>
                                    <key>redis-failover-retry-count</key>
                                    <value>0</value>
                            </property>
                            <property>
                                    <key>redis-failover-retry-interval</key>
                                    <value>5</value>
                            </property>
                            <property>
                                    <key>redis-update-timeout</key>
                                    <value>10</value>
                            </property>
                    </properties>
            </session-cluster>
            <system-clustering-framework>
                    <transport>MESH</transport>
                    <transport-address>224.0.0.1</transport-address>
                    <transport-port>12488</transport-port>
                    <leader-discovery-timeout>3000</leader-discovery-timeout>
                    <failure-detection-timeout>3000</failure-detection-timeout>
                    <max-thread-pool-size>10</max-thread-pool-size>
                    <min-thread-pool-size>0</min-thread-pool-size>
            </system-clustering-framework>
            <servers>
                    <server>
                            <name>%SERVERNAME%</name>
                            <jvm-config>
                                    <jvm-option>-Xms512m -Xmx512m</jvm-option>
                            </jvm-config>
                            <use-web-engine>true</use-web-engine>
                            <use-ejb-engine>false</use-ejb-engine>
                            <use-jms-engine>false</use-jms-engine>
                            <class-ftp>true</class-ftp>
                            <listeners>
                                    <base>base</base>
                                    <listener>
                                            <name>base</name>
                                            <listen-address>0.0.0.0</listen-address>
                                            <listen-port>9736</listen-port>
                                    </listener>
                                    <listener>
                                            <name>http-server</name>
                                            <listen-address>0.0.0.0</listen-address>
                                            <listen-port>8080</listen-port>
                                            <keep-alive-timeout>600000</keep-alive-timeout>
                                    </listener>
                            </listeners>
                            <web-engine>
                                    <blocked-url-patterns>
                                            <deny-last-space-character>true</deny-last-space-character>
                                            <deny-null-character>true</deny-null-character>
                                            <encoded-pattern>%00</encoded-pattern>
                                            <encoded-pattern>%23</encoded-pattern>
                                            <encoded-pattern>%2e</encoded-pattern>
                                            <encoded-pattern>%2f</encoded-pattern>
                                            <encoded-pattern>%5c</encoded-pattern>
                                            <encoded-pattern>#</encoded-pattern>
                                            <encoded-pattern>\</encoded-pattern>
                                    </blocked-url-patterns>
                                    <web-connections>
                                            <http-listener>
                                                    <name>http</name>
                                                    <server-listener-ref>http-server</server-listener-ref>
                                                    <thread-pool>
                                                            <min>10</min>
                                                            <max>20</max>
                                                    </thread-pool>
                                            </http-listener>
                                    </web-connections>
                            </web-engine>
                            <jms-engine>
                                    <service-config>
                                            <name>default</name>
                                            <listener-name>jms</listener-name>
                                            <client-limit>100</client-limit>
                                            <client-keepalive-timeout>20</client-keepalive-timeout>
                                    </service-config>
                                    <thread-pool>
                                            <min>10</min>
                                            <max>20</max>
                                    </thread-pool>
                                    <connection-factory>
                                            <type>nonxa</type>
                                            <name>ConnectionFactory</name>
                                    </connection-factory>
                                    <connection-factory>
                                            <type>xa</type>
                                            <name>XAConnectionFactory</name>
                                    </connection-factory>
                            </jms-engine>
                            <jms-resource>
                                    <destination>
                                            <type>queue</type>
                                            <name>ExamplesQueue</name>
                                    </destination>
                                    <destination>
                                            <type>topic</type>
                                            <name>ExamplesTopic</name>
                                    </destination>
                            </jms-resource>
                            <system-logging>
                                    <name>jeus</name>
                                    <level>INFO</level>
                                    <handler>
                                            <file-handler>
                                                    <name>fileHandler</name>
                                                    <valid-day>1</valid-day>
                                            </file-handler>
                                    </handler>
                            </system-logging>
                    </server>
            </servers>
            <deployed-applications>
                    <deployed-application>
                            <id>examples</id>
                            <path>/app/jeus</path>
                            <type>WAR</type>
                            <target-all-servers>true</target-all-servers>
                            <classloading>ISOLATED</classloading>
                            <use-fast-deploy>false</use-fast-deploy>
                            <keep-generated>false</keep-generated>
                            <shared>false</shared>
                            <context-path>/</context-path>
                            <node-java-context>false</node-java-context>
                    </deployed-application>
            </deployed-applications>
            <resources>
                <data-source>
                    <database>
                        <data-source-id>postgre</data-source-id>
                        <export-name>postgre</export-name>
                        <data-source-class-name>org.postgresql.ds.PGConnectionPoolDataSource</data-source-class-name>
                        <data-source-type>ConnectionPoolDataSource</data-source-type>
                        <vendor>others</vendor>
                        <user>inner</user>
                        <password>inner</password>
                        <login-timeout>0</login-timeout>
                        <auto-commit>DRIVER</auto-commit>
                        <stmt-query-timeout>0</stmt-query-timeout>
                        <pool-destroy-timeout>10000</pool-destroy-timeout>
                        <property>
                            <name>Url</name>
                            <value>jdbc:postgresql://svc-pgpool.db:5432/hfi</value>
                            <type>java.lang.String</type>
                        </property>
                        <support-xa-emulation>false</support-xa-emulation>
                        <connection-pool>
                            <pooling>
                                <min>10</min>
                                <max>20</max>
                                <step>1</step>
                                <period>360000</period>
                            </pooling>
                            <wait-free-connection>
                                <enable-wait>true</enable-wait>
                                <wait-time>10000</wait-time>
                            </wait-free-connection>
                            <max-use-count>0</max-use-count>
                            <dba-timeout>-1</dba-timeout>
                            <connection-validation>
                                <check-query>select 1</check-query>
                                <check-query-timeout>5000</check-query-timeout>
                                <non-validation-interval>60000</non-validation-interval>
                                <check-query-period>300000</check-query-period>
                                <check-query-retrial-count>0</check-query-retrial-count>
                                <destroy-policy-on-check-query>AllConnections</destroy-policy-on-check-query>
                            </connection-validation>
                            <stmt-caching-size>-1</stmt-caching-size>
                            <stmt-fetch-size>-1</stmt-fetch-size>
                            <connection-trace>
                                <enabled>false</enabled>
                                <get-connection-trace>true</get-connection-trace>
                                <auto-commit-trace>false</auto-commit-trace>
                            </connection-trace>
                            <use-sql-trace>false</use-sql-trace>
                            <keep-connection-handle-open>false</keep-connection-handle-open>
                        </connection-pool>
                    </database>
                    <database>
                        <data-source-id>mariadb</data-source-id>
                        <export-name>mariadb</export-name>
                        <data-source-class-name>org.mariadb.jdbc.MariaDbDataSource</data-source-class-name>
                        <data-source-type>ConnectionPoolDataSource</data-source-type>
                        <vendor>others</vendor>
                        <user>inner</user>
                        <password>inner</password>
                        <login-timeout>0</login-timeout>
                        <auto-commit>DRIVER</auto-commit>
                        <stmt-query-timeout>0</stmt-query-timeout>
                        <pool-destroy-timeout>10000</pool-destroy-timeout>
                        <property>
                            <name>Url</name>
                            <value>jdbc:mariadb://svc-mariadb.db:3306/hfi</value>
                            <type>java.lang.String</type>
                        </property>
                        <support-xa-emulation>false</support-xa-emulation>
                        <connection-pool>
                            <pooling>
                                <min>10</min>
                                <max>20</max>
                                <step>1</step>
                                <period>360000</period>
                            </pooling>
                            <wait-free-connection>
                                <enable-wait>true</enable-wait>
                                <wait-time>10000</wait-time>
                            </wait-free-connection>
                            <max-use-count>0</max-use-count>
                            <dba-timeout>-1</dba-timeout>
                            <connection-validation>
                                <check-query>select 1</check-query>
                                <check-query-timeout>5000</check-query-timeout>
                                <non-validation-interval>60000</non-validation-interval>
                                <check-query-period>300000</check-query-period>
                                <check-query-retrial-count>0</check-query-retrial-count>
                                <destroy-policy-on-check-query>AllConnections</destroy-policy-on-check-query>
                            </connection-validation>
                            <stmt-caching-size>-1</stmt-caching-size>
                            <stmt-fetch-size>-1</stmt-fetch-size>
                            <connection-trace>
                                <enabled>false</enabled>
                                <get-connection-trace>true</get-connection-trace>
                                <auto-commit-trace>false</auto-commit-trace>
                            </connection-trace>
                            <use-sql-trace>false</use-sql-trace>
                            <keep-connection-handle-open>false</keep-connection-handle-open>
                        </connection-pool>
                    </database>
                </data-source>
            </resources>
        <enable-webadmin>false</enable-webadmin>
    </domain>

                            
